# Generated by Django 5.1.1 on 2024-09-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
    ]
